In [1]:
# Tratamiento de datos
# ==============================================================================
import numpy as np
import pandas as pd

import re

import sidetable
import math

# Content
### Data:-

**Poster_Link** - Link of the poster that imdb using

**Series_Title** = Name of the movie

**Released_Year** - Year at which that movie released

**Certificate** - Certificate earned by that movie

**Runtime** - Total runtime of the movie

**Genre** - Genre of the movie

**IMDB_Rating** - Rating of the movie at IMDB site

**Overview** - mini story/ summary

**Meta_score** - Score earned by the movie

**Director** - Name of the Director

**Star1,Star2,Star3,Star4** - Name of the Stars

**Noofvotes** - Total number of votes

**Gross** - Money earned by that movie


# Inspiration

Analysis of the gross of a movie vs directors.

Analysis of the gross of a movie vs different - different stars.

Analysis of the Noofvotes of a movie vs directors.

Analysis of the Noofvotes of a movie vs different - different stars.

Which actor prefer which Genre more?

Which combination of actors are getting good IMDB_Rating maximum time?

Which combination of actors are getting good gross?

In [2]:
df_imbd = pd.read_csv("./imdb_top_1000.csv")
df_imbd.head(3)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"

In [3]:
df_imbd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [4]:
df_imbd["Director"].unique()
#hay 548 directores

array(['Frank Darabont', 'Francis Ford Coppola', 'Christopher Nolan',
       'Sidney Lumet', 'Peter Jackson', 'Quentin Tarantino',
       'Steven Spielberg', 'David Fincher', 'Robert Zemeckis',
       'Sergio Leone', 'Lana Wachowski', 'Martin Scorsese',
       'Irvin Kershner', 'Milos Forman', 'Thomas Kail', 'Bong Joon Ho',
       'Sudha Kongara', 'Fernando Meirelles', 'Hayao Miyazaki',
       'Roberto Benigni', 'Jonathan Demme', 'George Lucas',
       'Masaki Kobayashi', 'Akira Kurosawa', 'Frank Capra',
       'Todd Phillips', 'Damien Chazelle', 'Olivier Nakache',
       'Roman Polanski', 'Ridley Scott', 'Tony Kaye', 'Bryan Singer',
       'Luc Besson', 'Roger Allers', 'James Cameron',
       'Giuseppe Tornatore', 'Isao Takahata', 'Alfred Hitchcock',
       'Michael Curtiz', 'Charles Chaplin', 'Nadine Labaki', 'Can Ulkay',
       'Gayatri', 'Makoto Shinkai', 'Nitesh Tiwari', 'Bob Persichetti',
       'Anthony Russo', 'Lee Unkrich', 'Rajkumar Hirani', 'Aamir Khan',
       'Andrew Stanton', 'Florian Henckel von Donnersmarck',
       'Chan-wook Park', 'Stanley Kubrick', 'Hrishikesh Mukherjee',
       'Billy Wilder', 'Sam Mendes', 'Rahi Anil Barve', 'Sriram Raghavan',
       'Jeethu Joseph', 'Thomas Vinterberg', 'Asghar Farhadi',
       'Denis Villeneuve', 'Mehmet Ada Öztekin', 'Çagan Irmak',
       'Michel Gondry', 'Jean-Pierre Jeunet', 'Guy Ritchie',
       'Darren Aronofsky', 'Gus Van Sant', 'Majid Majidi',
       'John Lasseter', 'Mel Gibson', 'Elem Klimov', 'Brian De Palma',
       'Richard Marquand', 'Wolfgang Petersen', 'George Roy Hill',
       'David Lean', 'Stanley Donen', 'Vittorio De Sica', 'Orson Welles',
       'Fritz Lang', 'Aditya Dhar', 'Prashanth Neel', 'Peter Farrelly',
       'Martin McDonagh', 'Meghna Gulzar', 'S.S. Rajamouli',
       'Sergio Pablos', 'Nishikant Kamat', 'Vikas Bahl', 'Zaza Urushadze',
       'Rakeysh Omprakash Mehra', 'Anurag Kashyap',
       'Vikramaditya Motwane', 'Tigmanshu Dhulia', 'Juan José Campanella',
       "Gavin O'Connor", 'Pete Docter', 'Shimit Amin',
       'Paul Thomas Anderson', 'Guillermo del Toro', 'James McTeigue',
       'Sanjay Leela Bhansali', 'Ashutosh Gowariker',
       'Oliver Hirschbiegel', 'Ron Howard', 'Priyadarshan',
       'Curtis Hanson', 'Yavuz Turgul', 'Michael Mann',
       'Rajkumar Santoshi', 'Clint Eastwood', 'Emir Kusturica',
       'John McTiernan', 'Andrei Tarkovsky', 'Ingmar Bergman',
       'Moustapha Akkad', 'Ramesh Sippy', 'Terry Gilliam', 'John Sturges',
       'Robert Mulligan', 'Stanley Kramer', 'Jules Dassin',
       'Yasujirô Ozu', 'Joseph L. Mankiewicz', 'John Huston',
       'Ernst Lubitsch', 'Buster Keaton', 'Céline Sciamma',
       'Aniruddha Roy Chowdhury', 'Naoko Yamada', 'Oriol Paulo',
       'Xavier Dolan', 'Vishal Bhardwaj', 'James Mangold',
       'Lenny Abrahamson', 'Damián Szifron', 'Nuri Bilge Ceylan',
       'Umesh Shukla', 'Wes Anderson', 'Mamoru Hosoda', 'Anurag Basu',
       'Steve McQueen', 'Tom McCarthy', 'Tomm Moore', 'Sujoy Ghosh',
       'Zoya Akhtar', 'George Miller', 'Neeraj Pandey', 'David Yates',
       'Yôjirô Takita', 'Lasse Hallström', 'Adam Elliot', 'Dean DeBlois',
       'Sean Penn', 'Ethan Coen', 'Terry George', 'Je-kyu Kang',
       'Richard Linklater', 'Farhan Akhtar', 'Alejandro G. Iñárritu',
       'Hideaki Anno', 'M. Night Shyamalan', 'Peter Weir', 'Joel Coen',
       'Kar-Wai Wong', 'Danny Boyle', 'Mathieu Kassovitz',
       'Aditya Chopra', 'Krzysztof Kieslowski', 'Jim Sheridan',
       'Kaige Chen', 'Yimou Zhang', 'Rob Reiner', 'Oliver Stone',
       'Wim Wenders', 'John Carpenter', 'Alan Parker', 'Werner Herzog',
       'David Lynch', 'Terry Jones', 'Michael Cimino', 'John G. Avildsen',
       'Peter Bogdanovich', 'Jean-Pierre Melville', 'Stuart Rosenberg',
       'Gillo Pontecorvo', 'Luis Buñuel', 'Robert Aldrich', 'John Ford',
       'François Truffaut', 'William Wyler', 'Federico Fellini',
       'Elia Kazan', 'Henri-Georges Clouzot', 'Raoul Walsh', 'Carol Reed',
       'Michael Powell', 'Victor Fleming', 'Jean Renoir',
       'Carl Theodor Dreyer', 'F.W. Murnau', 'Clyde Bruckman',
       'Robert Wiene', 'Amit Ravindernath Sharma', 'Ericson Core',
       'Raja Menon', 'Kabir Khan', 'Garth Davis', 'Byron Howard',
       'Stephen Chbosky', 'Destin Daniel Cretton', 'Gareth Evans',
       'Morten Tyldum', 'James Gunn', 'Spike Jonze', 'José Padilha',
       'Tom Hooper', 'Tate Taylor', 'Tim Miller', 'Wilson Yip',
       'Karan Johar', 'Levent Semerci', 'Joss Whedon',
       'Vincent Paronnaud', 'Jean-Marc Vallée', 'Gabriele Muccino',
       'Edward Zwick', 'Paul Greengrass', 'Ki-duk Kim', 'Frank Miller',
       'Julian Schnabel', 'Ömer Faruk Sorak', 'Brad Bird',
       'Martin Campbell', 'Andrey Zvyagintsev', 'Alejandro Amenábar',
       'Nikkhil Advani', 'Andrew Lau', 'Gore Verbinski', 'Tim Burton',
       'Jae-young Kwak', 'Lars von Trier', 'Yilmaz Erdogan',
       'Richard Kelly', 'Satoshi Kon', 'Walter Salles', 'Thomas Jahn',
       'Billy Bob Thornton', 'Mike Leigh', 'Mamoru Oshii', 'Henry Selick',
       'Harold Ramis', 'Taylor Hackford', 'Martin Brest', 'Ron Clements',
       'Gary Trousdale', 'Kevin Costner', 'Spike Lee', 'Barry Levinson',
       'Katsuhiro Ôtomo', 'Louis Malle', 'Richard Attenborough',
       'Hal Ashby', 'Woody Allen', 'Mel Brooks', 'Franklin J. Schaffner',
       'William Friedkin', 'Norman Jewison', 'Bernardo Bertolucci',
       'Mike Nichols', 'Robert Wise', 'Jean-Luc Godard', 'Robert Rossen',
       'Howard Hawks', 'Otto Preminger', 'Richard Brooks',
       'Alexander Mackendrick', 'Charles Laughton', 'Nicholas Ray',
       'Robert Hamer', 'Jacques Tourneur', 'W.S. Van Dyke',
       'Lewis Milestone', 'Sergei M. Eisenstein', 'Rian Johnson',
       'Mukesh Chhabra', 'Hirokazu Koreeda', 'Noah Baumbach',
       'Luca Guadagnino', 'Ken Loach', 'Taika Waititi', 'Matt Ross',
       'John Carney', 'Dan Gilroy', 'J.J. Abrams', 'Michel Hazanavicius',
       'Doug Liman', 'Michael Haneke', 'Jacques Audiard', 'Duncan Jones',
       'Tomas Alfredson', 'Neill Blomkamp', 'Imtiaz Ali',
       'Cristian Mungiu', 'Richard Schenkman', 'Tarsem Singh', 'Ang Lee',
       'Christophe Barratier', 'Jon Favreau', 'Edgar Wright',
       'Fatih Akin', 'Alfonso Cuarón', 'Pedro Almodóvar', 'Danis Tanovic',
       "Shin'ichirô Watanabe", 'Fabián Bielinsky', 'Cameron Crowe',
       'Yoshifumi Kondô', 'Lee Tamahori', 'Tony Scott',
       'Yoshiaki Kawajiri', 'Bob Clark', 'John Landis', 'Bob Fosse',
       'George A. Romero', 'Alan J. Pakula', 'Alejandro Jodorowsky',
       'Sam Peckinpah', 'Anthony Harvey', 'John Frankenheimer',
       'Michelangelo Antonioni', 'Alain Resnais', 'Cecil B. DeMille',
       'Fred Zinnemann', 'Henry Koster', 'George Seaton', 'George Cukor',
       'Sam Wood', 'Merian C. Cooper', 'Tod Browning', 'Darius Marder',
       'Paolo Genovese', 'Theodore Melfi', 'Paul King',
       'Abhishek Chaubey', 'Travis Knight', 'Kenneth Lonergan',
       'Martin Zandvliet', 'Gareth Edwards', 'Greta Gerwig',
       'Dorota Kobiela', 'Matthew Warchus', 'Paolo Sorrentino',
       'Ritesh Batra', 'Shoojit Sircar', 'Don Hall', 'Richard Curtis',
       'Gauri Shinde', 'Josh Cooley', 'Adam McKay', 'Tetsuya Nakashima',
       'Jee-woon Kim', 'Jeong-beom Lee', 'F. Gary Gray', 'Hong-jin Na',
       'Niels Arden Oplev', 'Aaron Sorkin', 'David O. Russell',
       'Pierre Morel', 'Mark Herman', 'Joe Wright',
       'Nicolas Winding Refn', 'Jaco Van Dormael', 'Jonathan Dayton',
       'Yash Chopra', 'Anders Thomas Jensen', 'Roger Donaldson',
       'Mikael Håfström', 'Nick Cassavetes', 'Lukas Moodysson',
       'Sylvain Chomet', 'Kevin Reynolds', 'Boaz Yakin', 'Troy Duffy',
       'Joe Johnston', 'Andrew Adamson', 'Takeshi Kitano',
       'Andrew Niccol', 'George P. Cosmatos', 'David Mickey Evans',
       'James Ivory', 'Andrew Davis', 'Robert De Niro', 'Kevin Altieri',
       'John Woo', 'Jim Jarmusch', 'John Singleton', 'Penny Marshall',
       'Sam Raimi', 'John Hughes', 'Richard Donner', 'Roland Joffé',
       'Ivan Reitman', 'Philip Kaufman', 'Robert Benton',
       'Terrence Malick', 'René Laloux', 'Mel Stuart', 'John Schlesinger',
       'Terence Young', 'Arthur Penn', 'Robert Stevenson', 'Ken Annakin',
       'Jack Clayton', 'James Whale', 'Leo McCarey', 'Francis Lee',
       'David Leitch', 'Taylor Sheridan', 'Jordan Peele',
       'Christopher McQuarrie', 'Hannes Holm', 'Jemaine Clement',
       'James Simone', 'James Marsh', 'Matthew Vaughn', 'Josh Boone',
       'Alfonso Gomez-Rejon', 'Abdellatif Kechiche', 'Abhishek Kapoor',
       'Felix van Groeningen', 'Alexander Payne', 'Rich Moore',
       'Mark Osborne', 'Christopher Miller', 'Cary Joji Fukunaga',
       'Ben Affleck', 'Marc Webb', 'Shûsuke Kaneko', 'Shane Meadows',
       'Alex Garland', 'Susanne Bier', 'Kevin Macdonald', 'Paul McGuigan',
       'Christian Carion', 'Anton Corbijn', 'Nathan Greno',
       'Paul Verhoeven', 'Paul Haggis', 'Stephen Chow', 'Brad Anderson',
       'Sofia Coppola', 'Mike Newell', 'Peter Mullan', 'Wolfgang Becker',
       'Jessie Nelson', 'Stephen Daldry', 'John Cameron Mitchell',
       'Steven Soderbergh', 'Bob Gale', 'Trey Parker', 'Mike Judge',
       'Todd Solondz', 'Antoine Fuqua', 'James L. Brooks',
       'Francis Veber', 'Scott Hicks', 'Gregory Hoblit',
       'Kenneth Branagh', 'Michael Radford', 'Kevin Smith',
       'Robert Altman', 'Brian Henson', 'James Foley', 'Jon Avnet',
       'George Sluizer', 'Bruce Robinson', 'Jean-Jacques Annaud',
       'Nicholas Meyer', 'Ted Kotcheff', 'Robert Redford', 'Jim Abrahams',
       'Joseph Sargent', 'Robert Clouse', 'John Boorman', 'Don Siegel',
       'Brian G. Hutton', 'Gene Saks', 'Cy Endfield', 'Guy Hamilton',
       'J. Lee Thompson', 'Georges Franju', 'Charles Vidor',
       'James Algar', 'Todd Haynes', 'Aneesh Chaganty', 'Sean Baker',
       'Tyler Nilson', 'Sebastian Schipper', 'Deniz Gamze Ergüven',
       'Joseph Kosinski', 'Ryan Coogler', 'David Mackenzie',
       'Stephen Frears', 'Matt Reeves', 'David Ayer',
       'Hiromasa Yonebayashi', 'Bradley Cooper', 'Pierre Coffin',
       'Jonathan Levine', 'Daniel Monzón', 'Bennett Miller',
       'Ruben Fleischer', 'Dennis Gansel', 'John Lee Hancock',
       'David Cronenberg', 'Olivier Dahan', 'Ronny Yu', 'Neil Burger',
       'Zack Snyder', 'James Wan', 'Charlie Kaufman', 'Gregg Araki',
       'Yann Samuell', 'Marc Forster', 'Eric Bress', 'Kinji Fukasaku',
       'Chris Columbus', 'Ted Demme', 'Mary Harron', 'Tom Tykwer',
       'Tony Bancroft', 'Alex Proyas', 'Joel Schumacher', 'Jonathan Lynn',
       'Marc Caro', 'David Zucker', 'Mark Rydell', 'Walter Hill',
       'James Frawley', 'Martin Rosen', 'Wolfgang Reitherman',
       'Richard Lester', 'Blake Edwards', 'George Stevens'], dtype=object)

In [5]:
# Renombramos
df_imbd.rename(columns= {"No_of_Votes":"User_Ratings", "Star1":"Protagonist_1","Star2":"Protagonist_2", "Star3":"Supporting_actor_1","Star4":"Supporting_actor_2"},inplace=True)

In [6]:
df_imbd.head(1)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Protagonist_1,Protagonist_2,Supporting_actor_1,Supporting_actor_2,User_Ratings,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"

In [7]:
df_imbd['IMDB_Rating'] =df_imbd['IMDB_Rating'].apply(lambda x: x*10) #Para multiplicar x 10 cada valor de la columna

In [8]:
df_imbd.head(1)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Protagonist_1,Protagonist_2,Supporting_actor_1,Supporting_actor_2,User_Ratings,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,93.0,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"

In [9]:
patron= r"[0-9]{2,3}" #encuentra un numero y quedate con el , puedes encontrar 2 o 3 numeros.

def minutos(col):
   return re.findall(patron, col)

In [10]:
df_imbd["Runtime"]= df_imbd["Runtime"].apply(minutos).str[0] #str[0] te elimina los corchetes

In [11]:
df_imbd.head(1)

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Protagonist_1,Protagonist_2,Supporting_actor_1,Supporting_actor_2,User_Ratings,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142,Drama,93.0,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"

In [12]:

df_imbd=df_imbd.reindex(columns=[ 'Series_Title', 'Released_Year','Certificate', 'Runtime', 'Genre',
                                'IMDB_Rating', 'Meta_score', 'Director', 'Protagonist_1', 'Protagonist_2', 
                                'Supporting_actor_1', 'Supporting_actor_2', 'User_Ratings', 'Gross','Overview','Poster_Link'])

In [13]:
df_imbd.head(2)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Protagonist_1,Protagonist_2,Supporting_actor_1,Supporting_actor_2,User_Ratings,Gross,Overview,Poster_Link
0,The Shawshank Redemption,1994,A,142,Drama,93.0,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",Two imprisoned men bond over a number of years...,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,The Godfather,1972,A,175,"Crime, Drama",92.0,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",An organized crime dynasty's aging patriarch t...,https://m.media-amazon.com/images/M/MV5BM2MyNj...

    Ahora quiero pasar IMDB_Rating y Meta_score a INTEGER

In [14]:
df_imbd.IMDB_Rating= df_imbd.IMDB_Rating.astype(int)

In [15]:
# No me deja con esta por que tiene NAN , hay que eliminarlos
#df_imbd.Meta_score.astype(int)

In [16]:
df_imbd.isnull().sum() # no son muchos los elimino

Series_Title            0
Released_Year           0
Certificate           101
Runtime                 0
Genre                   0
IMDB_Rating             0
Meta_score            157
Director                0
Protagonist_1           0
Protagonist_2           0
Supporting_actor_1      0
Supporting_actor_2      0
User_Ratings            0
Gross                 169
Overview                0
Poster_Link             0
dtype: int64

In [17]:
df_imbd = df_imbd.dropna(subset=["Certificate","Meta_score", "Gross" ])

In [18]:
df_imbd.isnull().sum()

Series_Title          0
Released_Year         0
Certificate           0
Runtime               0
Genre                 0
IMDB_Rating           0
Meta_score            0
Director              0
Protagonist_1         0
Protagonist_2         0
Supporting_actor_1    0
Supporting_actor_2    0
User_Ratings          0
Gross                 0
Overview              0
Poster_Link           0
dtype: int64

In [19]:
df_imbd.Meta_score= df_imbd.Meta_score.astype(int) # ya son ambas int y para tableau no me aparecerán con .0 decimales

In [20]:
df_imbd.dtypes

Series_Title          object
Released_Year         object
Certificate           object
Runtime               object
Genre                 object
IMDB_Rating            int64
Meta_score             int64
Director              object
Protagonist_1         object
Protagonist_2         object
Supporting_actor_1    object
Supporting_actor_2    object
User_Ratings           int64
Gross                 object
Overview              object
Poster_Link           object
dtype: object

# Columna Genre

In [21]:
df_imbd["Genre"].unique()

array(['Drama', 'Crime, Drama', 'Action, Crime, Drama',
       'Action, Adventure, Drama', 'Biography, Drama, History',
       'Action, Adventure, Sci-Fi', 'Drama, Romance', 'Western',
       'Action, Sci-Fi', 'Biography, Crime, Drama',
       'Action, Adventure, Fantasy', 'Comedy, Drama, Thriller',
       'Adventure, Drama, Sci-Fi', 'Animation, Adventure, Family',
       'Drama, War', 'Crime, Drama, Fantasy', 'Comedy, Drama, Romance',
       'Crime, Drama, Mystery', 'Crime, Drama, Thriller', 'Drama, Music',
       'Biography, Comedy, Drama', 'Drama, Mystery, Sci-Fi',
       'Biography, Drama, Music', 'Crime, Mystery, Thriller',
       'Animation, Adventure, Drama', 'Adventure, Comedy, Sci-Fi',
       'Horror, Mystery, Thriller', 'Drama, Romance, War',
       'Comedy, Drama, Family', 'Animation, Drama, Fantasy',
       'Animation, Action, Adventure', 'Drama, Western',
       'Action, Adventure', 'Comedy, Drama', 'Drama, Mystery, Thriller',
       'Action, Drama, Mystery', 'Mystery, Thriller', 'Drama, Horror',
       'Drama, Mystery, War', 'Horror, Sci-Fi', 'Comedy',
       'Drama, Thriller, War', 'Adventure, Drama, War',
       'Drama, Romance, Sci-Fi', 'Comedy, Romance', 'Comedy, Crime',
       'Drama, Family, Sport', 'Animation, Adventure, Comedy',
       'Adventure, Drama, Thriller', 'Comedy, Crime, Drama',
       'Crime, Drama, Sci-Fi', 'Adventure, Sci-Fi',
       'Adventure, Biography, Drama', 'Adventure, Mystery, Thriller',
       'Mystery, Romance, Thriller', 'Comedy, Musical, Romance',
       'Crime, Drama, Film-Noir', 'Drama, Mystery',
       'Drama, Mystery, Romance', 'Action, Drama, Sport',
       'Drama, Fantasy, War', 'Action, Drama, Sci-Fi', 'Biography, Drama',
       'Action, Comedy, Crime', 'Animation, Family, Fantasy',
       'Action, Thriller', 'Action, Drama, War',
       'Biography, Drama, Sport', 'Adventure, Comedy, Fantasy',
       'Adventure, Drama, History', 'Comedy, Music, Romance',
       'Crime, Thriller', 'Adventure, Drama, Western',
       'Drama, Romance, Thriller', 'Drama, Thriller',
       'Adventure, Comedy, Crime', 'Action, Biography, Drama',
       'Adventure, Drama, Fantasy', 'Drama, Sport',
       'Adventure, Drama, Musical', 'Drama, Music, Romance',
       'Comedy, Crime, Romance', 'Comedy, Crime, Sport',
       'Adventure, Drama', 'Animation, Adventure, Fantasy',
       'Horror, Mystery, Sci-Fi', 'Drama, Fantasy, Music',
       'Action, Sci-Fi, Thriller', 'Drama, Horror, Thriller',
       'Drama, Film-Noir', 'Film-Noir, Mystery, Thriller',
       'Drama, History, Romance', 'Comedy, Drama, Music', 'Drama, Family',
       'Action, Crime, Thriller', 'Biography, Drama, Thriller',
       'Action, Adventure, Comedy', 'Animation, Biography, Drama',
       'Action, Mystery, Thriller', 'Crime, Drama, Romance',
       'Action, Adventure, Thriller', 'Comedy, Drama, Musical',
       'Crime, Drama, Musical', 'Mystery, Sci-Fi, Thriller',
       'Animation, Action, Crime', 'Comedy, Fantasy, Romance',
       'Drama, History, Thriller', 'Adventure, Family, Fantasy',
       'Drama, Fantasy, Romance', 'Adventure, Thriller', 'Horror',
       'Drama, Family, Musical', 'Biography, Drama, Family',
       'Action, Drama, Western', 'Drama, History',
       'Adventure, Comedy, Drama', 'Comedy, Drama, War', 'Drama, Sci-Fi',
       'Comedy, Horror', 'Action, Adventure, History',
       'Drama, Music, Mystery', 'Comedy, Music', 'Comedy, Family',
       'Drama, Music, Musical', 'Action, Adventure, Horror',
       'Biography, Drama, War', 'Action, Adventure, Western',
       'Comedy, Mystery, Romance', 'Drama, Thriller, Western',
       'Crime, Film-Noir, Thriller', 'Drama, Film-Noir, Romance',
       'Action, Adventure, Romance', 'Adventure, Horror, Sci-Fi',
       'Action, Drama, History', 'Adventure, Comedy, Family',
       'Drama, History, War', 'Animation, Biography, Crime',
       'Comedy, Drama, Fantasy', 'Adventure, Biography, Crime',
       'Adventure, Fantasy', 'Drama, History, Mystery',
       'Action, Comedy, Mystery', 'Animation, Comedy, Drama',
       'Adventure, Drama, Romance', 'Drama, Sci-Fi, Thriller',
       'Crime, Drama, History', 'Action, Comedy, Fantasy',
       'Family, Sci-Fi', 'Animation, Sci-Fi', 'Family, Fantasy, Musical',
       'Comedy, Family, Fantasy', 'Animation, Drama, Family',
       'Biography, Drama, Romance', 'Drama, History, Music',
       'Action, Drama', 'Animation, Action, Fantasy',
       'Animation, Comedy, Fantasy', 'Drama, Family, Fantasy',
       'Horror, Thriller', 'Comedy, Western', 'Drama, Horror, Mystery',
       'Animation, Comedy, Crime', 'Action, Adventure, Mystery',
       'Drama, Fantasy, Mystery', 'Action, Adventure, Family',
       'Drama, Horror, Sci-Fi', 'Action, Crime, Mystery',
       'Animation, Drama, Romance', 'Action, Biography, Crime',
       'Drama, War, Western', 'Adventure, Comedy, War',
       'Comedy, Music, Musical'], dtype=object)

In [22]:
df_imbd["Genre"]

0                             Drama
1                      Crime, Drama
2              Action, Crime, Drama
3                      Crime, Drama
4                      Crime, Drama
                   ...
990             Drama, War, Western
991          Adventure, Comedy, War
992    Animation, Adventure, Family
994          Comedy, Music, Musical
997             Drama, Romance, War
Name: Genre, Length: 714, dtype: object

In [23]:
df_imbd[["Genre_1","Genre_2","Genre_3"]] = df_imbd["Genre"].str.split(pat=", ", n=-1, expand=True)

In [24]:
df_imbd=df_imbd.reindex(columns=[ 'Series_Title', 'Released_Year','Certificate', 'Runtime', 'Genre', 'Genre_1', 'Genre_2', 'Genre_3', 
                                'IMDB_Rating', 'Meta_score', 'Director', 'Protagonist_1', 'Protagonist_2', 
                                'Supporting_actor_1', 'Supporting_actor_2', 'User_Ratings', 'Gross','Overview','Poster_Link'])

In [25]:
df_imbd.head()[:10]

,Series_Title,Released_Year,Certificate,Runtime,Genre,Genre_1,Genre_2,Genre_3,IMDB_Rating,Meta_score,Director,Protagonist_1,Protagonist_2,Supporting_actor_1,Supporting_actor_2,User_Ratings,Gross,Overview,Poster_Link
0,The Shawshank Redemption,1994,A,142,Drama,Drama,None,None,93,80,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",Two imprisoned men bond over a number of years...,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,The Godfather,1972,A,175,"Crime, Drama",Crime,Drama,None,92,100,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",An organized crime dynasty's aging patriarch t...,https://m.media-amazon.com/images/M/MV5BM2MyNj...
2,The Dark Knight,2008,UA,152,"Action, Crime, Drama",Action,Crime,Drama,90,84,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444",When the menace known as the Joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,The Godfather: Part II,1974,A,202,"Crime, Drama",Crime,Drama,None,90,90,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...
4,12 Angry Men,1957,U,96,"Crime, Drama",Crime,Drama,None,90,96,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",A jury holdout attempts to prevent a miscarria...,https://m.media-amazon.com/images/M/MV5BMWU4N2...

In [26]:
df_imbd.to_csv('Tableau_limpio.csv')

# Opción 1

In [27]:
# x= pd.Series(list)

In [28]:
# for col in df_genres.columns:
#     try:
#         x= pd.Series(list(df_genres[col].unique()))
#     except:
#         pass

In [29]:
# x # ya sabemos que hay 18 generos